# Generated by Django 5.2.1 on 2025-06-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='mot_de_passe',
            new_name='le_mot_de_passe',
        ),
    ]
